version: '3.8'

services:
  nginx:
    container_name: nginx
    build: ./docker/nginx
    env_file:
      - .env
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    volumes:
      - ./store/data/certificates:/etc/nginx/certificates:ro
      - ./public:/var/www/html/public:ro
      - ./docker/nginx/conf/default.conf:/etc/nginx/conf.d/default.conf
      - ./store/logs/nginx:/var/log/nginx
    ports:
      - "80:80"
      - "443:443"
    entrypoint:
      - "nginx"
      - "-g"
      - "daemon off;"
    restart: always
    stdin_open: true
    tty: true

  wg-easy:
    env_file:
      - .env
    container_name: wg-easy
    build: ./docker/wg-easy
    volumes:
      - ./store/data/wg-easy:/etc/wireguard
    ports:
      - "51820:51820/udp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1