version: '3.8'

services:
  proxy:
    container_name: 'dynamic_nginx_proxy'
    build: ./.docker/proxy
    volumes:
      - ./.docker/proxy/conf/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certificates:/etc/nginx/certificates:ro
      - ./public:/var/www/html/public:ro
    entrypoint:
      - "nginx"
      - "-g"
      - "daemon off;"
    ports:
      - '80:80'
      - '443:443'
    restart: always
    stdin_open: true
    tty: true
